require("vnext.config.options")
require("vnext.config.mappings")
require("vnext.config.lazy")
require("vnext.config.plugin-mappings")
require("vnext.config.colors")
-- require("vnext.config.autocmds")
